<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\Distillery;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistillerySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seedDistilleries = [
            ['name'=>"Adelaide Hills", 'country'=>"Australia",],
            ['name'=>"Adelaide Hills", 'country'=>"Australia",],
            ['name'=>"Animus", 'country'=>"Australia",],
            ['name'=>"Animus", 'country'=>"Australia",],
            ['name'=>"Animus", 'country'=>"Australia",],
            ['name'=>"Anther", 'country'=>"Australia",],
            ['name'=>"Applewood", 'country'=>"Australia",],
            ['name'=>"Archie Rose", 'country'=>"Australia",],
            ['name'=>"Australian", 'country'=>"Australia",],
            ['name'=>"Black Brewing", 'country'=>"Australia",],
            ['name'=>"Blind Tiger", 'country'=>"Australia",],
            ['name'=>"Brogan's Way", 'country'=>"Australia",],
            ['name'=>"Brogan's Way", 'country'=>"Australia",],
            ['name'=>"Canberra", 'country'=>"Australia",],
            ['name'=>"Distillery Botanica", 'country'=>"Australia",],
            ['name'=>"Dune Distilling", 'country'=>"Australia",],
            ['name'=>"Four Pillars", 'country'=>"Australia",],
            ['name'=>"Four Pillars", 'country'=>"Australia",],
            ['name'=>"Four Pillars", 'country'=>"Australia",],
            ['name'=>"Four Pillars", 'country'=>"Australia",],
            ['name'=>"Four Pillars", 'country'=>"Australia",],
            ['name'=>"Four Pillars", 'country'=>"Australia",],
            ['name'=>"Four Pillars", 'country'=>"Australia",],
            ['name'=>"Four Pillars", 'country'=>"Australia",],
            ['name'=>"Four Pillars", 'country'=>"Australia",],
            ['name'=>"Four Pillars", 'country'=>"Australia",],
            ['name'=>"Four Pillars", 'country'=>"Australia",],
            ['name'=>"Four Pillars", 'country'=>"Australia",],
            ['name'=>"Four Pillars", 'country'=>"Australia",],
            ['name'=>"Four Pillars", 'country'=>"Australia",],
            ['name'=>"Four Pillars", 'country'=>"Australia",],
            ['name'=>"Gin Gin Gin", 'country'=>"Australia",],
            ['name'=>"Harman's Estate", 'country'=>"Australia",],
            ['name'=>"Harris River Estate", 'country'=>"Australia",],
            ['name'=>"Hartshorn", 'country'=>"Australia",],
            ['name'=>"Helfire", 'country'=>"Australia",],
            ['name'=>"High Spirits", 'country'=>"Australia",],
            ['name'=>"Hippocampus", 'country'=>"Australia",],
            ['name'=>"Hippocampus", 'country'=>"Australia",],
            ['name'=>"Husk", 'country'=>"Australia",],
            ['name'=>"Husk", 'country'=>"Australia",],
            ['name'=>"Ironbark", 'country'=>"Australia",],
            ['name'=>"Kangaroo Island", 'country'=>"Australia",],
            ['name'=>"Kangaroo Island", 'country'=>"Australia",],
            ['name'=>"Lark", 'country'=>"Australia",],
            ['name'=>"Loch", 'country'=>"Australia",],
            ['name'=>"Manly Spirits", 'country'=>"Australia",],
            ['name'=>"Manly Spirits", 'country'=>"Australia",],
            ['name'=>"Margaret River", 'country'=>"Australia",],
            ['name'=>"Margaret River", 'country'=>"Australia",],
            ['name'=>"Margaret River", 'country'=>"Australia",],
            ['name'=>"McHenry", 'country'=>"Australia",],
            ['name'=>"Melbourne Gin Co.", 'country'=>"Australia",],
            ['name'=>"Melbourne Gin Co.", 'country'=>"Australia",],
            ['name'=>"Mt Uncle", 'country'=>"Australia",],
            ['name'=>"Mt Uncle", 'country'=>"Australia",],
            ['name'=>"Never Never", 'country'=>"Australia",],
            ['name'=>"Never Never", 'country'=>"Australia",],
            ['name'=>"Old Young's", 'country'=>"Australia",],
            ['name'=>"Old Young's", 'country'=>"Australia",],
            ['name'=>"Old Young's", 'country'=>"Australia",],
            ['name'=>"Old Young's", 'country'=>"Australia",],
            ['name'=>"Old Young's", 'country'=>"Australia",],
            ['name'=>"Old Young's", 'country'=>"Australia",],
            ['name'=>"Old Young's", 'country'=>"Australia",],
            ['name'=>"Old Young's", 'country'=>"Australia",],
            ['name'=>"Old Young's", 'country'=>"Australia",],
            ['name'=>"Old Young's", 'country'=>"Australia",],
            ['name'=>"Old Young's", 'country'=>"Australia",],
            ['name'=>"Old Young's", 'country'=>"Australia",],
            ['name'=>"Old Young's", 'country'=>"Australia",],
            ['name'=>"Old Young's", 'country'=>"Australia",],
            ['name'=>"Old Young's", 'country'=>"Australia",],
            ['name'=>"Old Young's", 'country'=>"Australia",],
            ['name'=>"Old Young's", 'country'=>"Australia",],
            ['name'=>"Patient Wolf", 'country'=>"Australia",],
            ['name'=>"Patient Wolf", 'country'=>"Australia",],
            ['name'=>"Prohibition", 'country'=>"Australia",],
            ['name'=>"Running with Thieves", 'country'=>"Australia",],
            ['name'=>"Shene Estate", 'country'=>"Australia",],
            ['name'=>"Sin Gin", 'country'=>"Australia",],
            ['name'=>"Sin Gin", 'country'=>"Australia",],
            ['name'=>"Sin Gin", 'country'=>"Australia",],
            ['name'=>"Sin Gin", 'country'=>"Australia",],
            ['name'=>"Sin Gin", 'country'=>"Australia",],
            ['name'=>"Sin Gin", 'country'=>"Australia",],
            ['name'=>"Sin Gin", 'country'=>"Australia",],
            ['name'=>"Spirit Bond", 'country'=>"Australia",],
            ['name'=>"Spirit of Little Things", 'country'=>"Australia",],
            ['name'=>"Spirit of Little Things", 'country'=>"Australia",],
            ['name'=>"Stone Pine", 'country'=>"Australia",],
            ['name'=>"Stone Pine", 'country'=>"Australia",],
            ['name'=>"Stone Pine", 'country'=>"Australia",],
            ['name'=>"Tattarang Springs", 'country'=>"Australia",],
            ['name'=>"Tiny Bear", 'country'=>"Australia",],
            ['name'=>"Wandering", 'country'=>"Australia",],
            ['name'=>"West Winds", 'country'=>"Australia",],
            ['name'=>"West Winds", 'country'=>"Australia",],
            ['name'=>"West Winds", 'country'=>"Australia",],
            ['name'=>"West Winds", 'country'=>"Australia",],
            ['name'=>"West Winds", 'country'=>"Australia",],
            ['name'=>"West Winds", 'country'=>"Australia",],
            ['name'=>"West Winds", 'country'=>"Australia",],
            ['name'=>"Winston Quinn", 'country'=>"Australia",],
            ['name'=>"Reisetbauer", 'country'=>"Austria",],
            ['name'=>"Domaine Pinnacle", 'country'=>"Canada",],
            ['name'=>"Park", 'country'=>"Canada",],
            ['name'=>"Ableforth", 'country'=>"England",],
            ['name'=>"Beefeater", 'country'=>"England",],
            ['name'=>"Berry Bros & Rudd", 'country'=>"England",],
            ['name'=>"Bombay Sapphire", 'country'=>"England",],
            ['name'=>"Bombay Sapphire", 'country'=>"England",],
            ['name'=>"Brentingby", 'country'=>"England",],
            ['name'=>"Broker's", 'country'=>"England",],
            ['name'=>"Bulldog", 'country'=>"England",],
            ['name'=>"Capreolus", 'country'=>"England",],
            ['name'=>"Cotswolds", 'country'=>"England",],
            ['name'=>"Chase", 'country'=>"England",],
            ['name'=>"Chase", 'country'=>"England",],
            ['name'=>"Greenalls", 'country'=>"England",],
            ['name'=>"Hayman", 'country'=>"England",],
            ['name'=>"Hayman", 'country'=>"England",],
            ['name'=>"Hayman", 'country'=>"England",],
            ['name'=>"Jinzu", 'country'=>"England",],
            ['name'=>"London Distillery", 'country'=>"England",],
            ['name'=>"Love Delhi", 'country'=>"England",],
            ['name'=>"Manchester", 'country'=>"England",],
            ['name'=>"Oxford Artisan Distillery", 'country'=>"England",],
            ['name'=>"Pleasure Gardens", 'country'=>"England",],
            ['name'=>"Plymouth", 'country'=>"England",],
            ['name'=>"Plymouth", 'country'=>"England",],
            ['name'=>"Portobello Star", 'country'=>"England",],
            ['name'=>"Ramsbury Estate", 'country'=>"England",],
            ['name'=>"Reformed Spirits", 'country'=>"England",],
            ['name'=>"Sacred", 'country'=>"England",],
            ['name'=>"Silent Pool", 'country'=>"England",],
            ['name'=>"Sipsmith", 'country'=>"England",],
            ['name'=>"Sipsmith", 'country'=>"England",],
            ['name'=>"Sovereign", 'country'=>"England",],
            ['name'=>"Thames Distillers", 'country'=>"England",],
            ['name'=>"Thames Distillers", 'country'=>"England",],
            ['name'=>"Warner Edwards", 'country'=>"England",],
            ['name'=>"Warner Edwards", 'country'=>"England",],
            ['name'=>"Whitley Neill", 'country'=>"England",],
            ['name'=>"Whitley Neill", 'country'=>"England",],
            ['name'=>"Kyro", 'country'=>"Finland",],
            ['name'=>"Ferrand", 'country'=>"France",],
            ['name'=>"Gabriel Boudier", 'country'=>"France",],
            ['name'=>"Albfink", 'country'=>"Germany",],
            ['name'=>"Berliner Brandstifter", 'country'=>"Germany",],
            ['name'=>"Capulet & Montague", 'country'=>"Germany",],
            ['name'=>"Elephant", 'country'=>"Germany",],
            ['name'=>"Gansloser", 'country'=>"Germany",],
            ['name'=>"Schwarzwald", 'country'=>"Germany",],
            ['name'=>"Schwarzwald", 'country'=>"Germany",],
            ['name'=>"Stauffenberg", 'country'=>"Germany",],
            ['name'=>"The Duke", 'country'=>"Germany",],
            ['name'=>"The Duke", 'country'=>"Germany",],
            ['name'=>"The Duke", 'country'=>"Germany",],
            ['name'=>"Ziegler", 'country'=>"Germany",],
            ['name'=>"Elephant", 'country'=>"Germany",],
            ['name'=>"Isfjord", 'country'=>"Greenland",],
            ['name'=>"Dingle", 'country'=>"Ireland",],
            ['name'=>"Midleton", 'country'=>"Ireland",],
            ['name'=>"Pearse Lyons", 'country'=>"Ireland",],
            ['name'=>"Shed Distillery", 'country'=>"Ireland",],
            ['name'=>"Shed Distillery", 'country'=>"Ireland",],
            ['name'=>"Campari", 'country'=>"Italy",],
            ['name'=>"Poli", 'country'=>"Italy",],
            ['name'=>"Torino", 'country'=>"Italy",],
            ['name'=>"Torino", 'country'=>"Italy",],
            ['name'=>"Torino", 'country'=>"Italy",],
            ['name'=>"Beam Suntory", 'country'=>"Japan",],
            ['name'=>"Kyoto", 'country'=>"Japan",],
            ['name'=>"Kyoto", 'country'=>"Japan",],
            ['name'=>"Kyoto", 'country'=>"Japan",],
            ['name'=>"Cross Keys", 'country'=>"Latvia",],
            ['name'=>"Katan", 'country'=>"Mexico",],
            ['name'=>"Mezcal", 'country'=>"Mexico",],
            ['name'=>"Toorank", 'country'=>"Netherlands",],
            ['name'=>"Rademon Estate", 'country'=>"Northern Ireland",],
            ['name'=>"Bareksten", 'country'=>"Norway",],
            ['name'=>"Norske Brenneri", 'country'=>"Norway",],
            ['name'=>"Lighthouse", 'country'=>"NZ",],
            ['name'=>"Lighthouse", 'country'=>"NZ",],
            ['name'=>"Rogue Society", 'country'=>"NZ",],
            ['name'=>"Rogue Society", 'country'=>"NZ",],
            ['name'=>"Simply Pure", 'country'=>"NZ",],
            ['name'=>"Glaswegin", 'country'=>"Scotland",],
            ['name'=>"Balmenach", 'country'=>"Scotland",],
            ['name'=>"Blackwoods", 'country'=>"Scotland",],
            ['name'=>"Blackwoods", 'country'=>"Scotland",],
            ['name'=>"Bruichladdich", 'country'=>"Scotland",],
            ['name'=>"Cadenhead", 'country'=>"Scotland",],
            ['name'=>"Cameronbridge", 'country'=>"Scotland",],
            ['name'=>"Cameronbridge", 'country'=>"Scotland",],
            ['name'=>"Cameronbridge", 'country'=>"Scotland",],
            ['name'=>"Edinburgh", 'country'=>"Scotland",],
            ['name'=>"Edinburgh", 'country'=>"Scotland",],
            ['name'=>"Edinburgh", 'country'=>"Scotland",],
            ['name'=>"Edinburgh", 'country'=>"Scotland",],
            ['name'=>"Glasgow", 'country'=>"Scotland",],
            ['name'=>"Hendrick's", 'country'=>"Scotland",],
            ['name'=>"Hendrick's", 'country'=>"Scotland",],
            ['name'=>"Hendrick's", 'country'=>"Scotland",],
            ['name'=>"Isle of Harris", 'country'=>"Scotland",],
            ['name'=>"Hope on Hopkins", 'country'=>"South Africa",],
            ['name'=>"Six Dogs", 'country'=>"South Africa",],
            ['name'=>"Atlantic Galician", 'country'=>"Spain",],
            ['name'=>"Campeny", 'country'=>"Spain",],
            ['name'=>"Herno", 'country'=>"Sweden",],
            ['name'=>"Spirit of Hven", 'country'=>"Sweden",],
            ['name'=>"Strane", 'country'=>"Sweden",],
            ['name'=>"Strane", 'country'=>"Sweden",],
            ['name'=>"Anchor", 'country'=>"USA",],
            ['name'=>"St George", 'country'=>"USA",],
            ['name'=>"St George", 'country'=>"USA",],
            ['name'=>"Tuthilltown", 'country'=>"USA",],
            ['name'=>"Elm", 'country'=>"USA",],
            ['name'=>"Da Mhile", 'country'=>"Wales",],
            ['name'=>"Da Mhile", 'country'=>"Wales",],
            ['name'=>"Penderyn", 'country'=>"Wales",],
            ['name'=>"Penderyn", 'country'=>"Wales",],

        ];

        foreach ($seedDistilleries as $seed) {
            $cid = Country::where('name', $seed['country'])->get()->pluck("_id");
            $data = ['name' => $seed['name'], 'country_id' => $cid[0],];
            echo $cid."\n";
            DB::Collection('distilleries')
                ->where('name', $seed['name'])
                ->where('country_id', $cid[0])
                ->update($data, ['upsert' => true]);
        }
    }
}
