<?php

namespace Database\Seeders;

use App\Models\Distillery;
use App\Models\Gin;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GinSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $ginSeeder = [
            ['name'=>"78 Degrees", 'distillery'=>"Adelaide Hills", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Green Ant", 'distillery'=>"Adelaide Hills", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Ambrosian", 'distillery'=>"Animus", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Arboretum", 'distillery'=>"Animus", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Classic dry", 'distillery'=>"Animus", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Distilled", 'distillery'=>"Anther", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Applewood Gin", 'distillery'=>"Applewood", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Signature Dry", 'distillery'=>"Archie Rose", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Perth gin", 'distillery'=>"Australian", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Still Black", 'distillery'=>"Black Brewing", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Organic", 'distillery'=>"Blind Tiger", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Hearts Afire", 'distillery'=>"Brogan's Way", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Royal Blood", 'distillery'=>"Brogan's Way", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Canberra Gin", 'distillery'=>"Canberra", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Garden Grow", 'distillery'=>"Distillery Botanica", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Dune", 'distillery'=>"Dune Distilling", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Barrel aged", 'distillery'=>"Four Pillars", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Bloody Shiraz 2020", 'distillery'=>"Four Pillars", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Bloody Shiraz 2021", 'distillery'=>"Four Pillars", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Cousin Vera's", 'distillery'=>"Four Pillars", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Changing Seasons", 'distillery'=>"Four Pillars", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Christmas gin 2017", 'distillery'=>"Four Pillars", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Four Pillars Navy", 'distillery'=>"Four Pillars", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Modern Australian", 'distillery'=>"Four Pillars", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Olive Leaf", 'distillery'=>"Four Pillars", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Rare Dry", 'distillery'=>"Four Pillars", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Rarer Dry", 'distillery'=>"Four Pillars", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Rarest Dry", 'distillery'=>"Four Pillars", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Spice Trade", 'distillery'=>"Four Pillars", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Spiced Negroni", 'distillery'=>"Four Pillars", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Sticky Carpet", 'distillery'=>"Four Pillars", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Shiraz", 'distillery'=>"Gin Gin Gin", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Gin Gin Gin", 'distillery'=>"Harman's Estate", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Boodja", 'distillery'=>"Harris River Estate", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Sheep Whey", 'distillery'=>"Hartshorn", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Hellfire", 'distillery'=>"Helfire", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"High Spirits Dry Gin", 'distillery'=>"High Spirits", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Hippocampus", 'distillery'=>"Hippocampus", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Jungle Gin", 'distillery'=>"Hippocampus", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Ink", 'distillery'=>"Husk", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Ink Sloe and Berry", 'distillery'=>"Husk", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Ironbark 313", 'distillery'=>"Ironbark", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"KIS Wild", 'distillery'=>"Kangaroo Island", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Old Tom aged", 'distillery'=>"Kangaroo Island", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Forty Spotted", 'distillery'=>"Lark", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"The Weaver", 'distillery'=>"Loch", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Australia Dry", 'distillery'=>"Manly Spirits", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Coastal Citrus", 'distillery'=>"Manly Spirits", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Giniversity - Australian Native", 'distillery'=>"Margaret River", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Giniversity - Botanical", 'distillery'=>"Margaret River", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Giniversity - London Dry", 'distillery'=>"Margaret River", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Parliamentary Librarian's", 'distillery'=>"McHenry", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"MGC Dry Gin", 'distillery'=>"Melbourne Gin Co.", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Single Shot", 'distillery'=>"Melbourne Gin Co.", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Botanic Australis", 'distillery'=>"Mt Uncle", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Botanic Australis Navy", 'distillery'=>"Mt Uncle", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Southern Strength", 'distillery'=>"Never Never", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Triple Juniper", 'distillery'=>"Never Never", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Cider", 'distillery'=>"Old Young's", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Common", 'distillery'=>"Old Young's", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Christmas Tree", 'distillery'=>"Old Young's", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"F*ck.Bushfires", 'distillery'=>"Old Young's", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"F*ck.Covid", 'distillery'=>"Old Young's", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Forager of the valley", 'distillery'=>"Old Young's", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Gingin Gin", 'distillery'=>"Old Young's", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Heat of the moment", 'distillery'=>"Old Young's", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"JÃ¶rd", 'distillery'=>"Old Young's", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Lilly Pilly old Tom", 'distillery'=>"Old Young's", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Marukatta", 'distillery'=>"Old Young's", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Orange and Saffron", 'distillery'=>"Old Young's", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Pawpaw", 'distillery'=>"Old Young's", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Pickled", 'distillery'=>"Old Young's", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Rise and shine", 'distillery'=>"Old Young's", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Six Seasons", 'distillery'=>"Old Young's", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Very Berry", 'distillery'=>"Old Young's", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Blackthorn", 'distillery'=>"Patient Wolf", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Summer Thyme", 'distillery'=>"Patient Wolf", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Prohibition", 'distillery'=>"Prohibition", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Trial batch 002 London Dry", 'distillery'=>"Running with Thieves", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Poltergeist Unfiltered", 'distillery'=>"Shene Estate", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Anger", 'distillery'=>"Sin Gin", 'country'=>"Australia", 'notes'=>'Mini','rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Envy", 'distillery'=>"Sin Gin", 'country'=>"Australia", 'notes'=>'Mini','rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Greed", 'distillery'=>"Sin Gin", 'country'=>"Australia", 'notes'=>'Mini','rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Lust", 'distillery'=>"Sin Gin", 'country'=>"Australia", 'notes'=>'Mini','rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Pride", 'distillery'=>"Sin Gin", 'country'=>"Australia", 'notes'=>'Mini','rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Sloth", 'distillery'=>"Sin Gin", 'country'=>"Australia", 'notes'=>'Mini','rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Wrath", 'distillery'=>"Sin Gin", 'country'=>"Australia", 'notes'=>'Mini','rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"SÃ¼d Polaire Expedition", 'distillery'=>"Spirit Bond", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Australian botanical", 'distillery'=>"Spirit of Little Things", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Australian dry", 'distillery'=>"Spirit of Little Things", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Japhet White", 'distillery'=>"Stone Pine", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Orange Blossom", 'distillery'=>"Stone Pine", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Original Dry", 'distillery'=>"Stone Pine", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Australian Botanical", 'distillery'=>"Tattarang Springs", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Sailor", 'distillery'=>"Tiny Bear", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Nomad", 'distillery'=>"Wandering", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Broadside", 'distillery'=>"West Winds", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Captain's Cut", 'distillery'=>"West Winds", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Cutlass", 'distillery'=>"West Winds", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Christmas dry", 'distillery'=>"West Winds", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Davidson Plum", 'distillery'=>"West Winds", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Maidenii Voyage", 'distillery'=>"West Winds", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Margaret River Dry Gin", 'distillery'=>"West Winds", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Dry cut", 'distillery'=>"Winston Quinn", 'country'=>"Australia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Blue", 'distillery'=>"Reisetbauer", 'country'=>"Austria", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Ungava", 'distillery'=>"Domaine Pinnacle", 'country'=>"Canada", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"RoW",],
            ['name'=>"Alpine Dry", 'distillery'=>"Park", 'country'=>"Canada", 'notes'=>'Mini','rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"RoW",],
            ['name'=>"Bathtub", 'distillery'=>"Ableforth", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Beefeater 24", 'distillery'=>"Beefeater", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"No. 3", 'distillery'=>"Berry Bros & Rudd", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Bombay Sapphire Dry Gin", 'distillery'=>"Bombay Sapphire", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Star of Bombay", 'distillery'=>"Bombay Sapphire", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Brentingby London Dry", 'distillery'=>"Brentingby", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Broker's Gin", 'distillery'=>"Broker's", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Bulldog", 'distillery'=>"Bulldog", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Garden Tiger", 'distillery'=>"Capreolus", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Cotswolds Dry Gin", 'distillery'=>"Cotswolds", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Great British", 'distillery'=>"Chase", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Mulberry and Sloe", 'distillery'=>"Chase", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Bloom", 'distillery'=>"Greenalls", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Old Tom", 'distillery'=>"Hayman", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Sloe", 'distillery'=>"Hayman", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Small gin", 'distillery'=>"Hayman", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Jinzu", 'distillery'=>"Jinzu", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Dodd's", 'distillery'=>"London Distillery", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Love Delhi", 'distillery'=>"Love Delhi", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Zymurgorium citrus", 'distillery'=>"Manchester", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Oxford dry", 'distillery'=>"Oxford Artisan Distillery", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Marylebone", 'distillery'=>"Pleasure Gardens", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Plymouth Sloe", 'distillery'=>"Plymouth", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"PlymouthNavy", 'distillery'=>"Plymouth", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Portobello Road No. 171", 'distillery'=>"Portobello Star", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Ramsbury", 'distillery'=>"Ramsbury Estate", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Martin Miller's - Westbourne", 'distillery'=>"Reformed Spirits", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Christmas Pudding", 'distillery'=>"Sacred", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Silent Pool", 'distillery'=>"Silent Pool", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Sipsmith London Dry", 'distillery'=>"Sipsmith", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Sipsmith V J O P", 'distillery'=>"Sipsmith", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Liverpool", 'distillery'=>"Sovereign", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Fords", 'distillery'=>"Thames Distillers", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"London No. 1", 'distillery'=>"Thames Distillers", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Harrington Dry", 'distillery'=>"Warner Edwards", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Victoria's Rhubarb", 'distillery'=>"Warner Edwards", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Original Dry Gin", 'distillery'=>"Whitley Neill", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Rhubarb & Ginger Gin", 'distillery'=>"Whitley Neill", 'country'=>"England", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Napue", 'distillery'=>"Kyro", 'country'=>"Finland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Citadelle", 'distillery'=>"Ferrand", 'country'=>"France", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Saffron", 'distillery'=>"Gabriel Boudier", 'country'=>"France", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Albfink Aged", 'distillery'=>"Albfink", 'country'=>"Germany", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Berlin", 'distillery'=>"Berliner Brandstifter", 'country'=>"Germany", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Ferdinand's Saar Dry", 'distillery'=>"Capulet & Montague", 'country'=>"Germany", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Elephant", 'distillery'=>"Elephant", 'country'=>"Germany", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Black - Distillers cut", 'distillery'=>"Gansloser", 'country'=>"Germany", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Monkey 47", 'distillery'=>"Schwarzwald", 'country'=>"Germany", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Monkey 47 Sloe", 'distillery'=>"Schwarzwald", 'country'=>"Germany", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Stauffenberg", 'distillery'=>"Stauffenberg", 'country'=>"Germany", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Munich Dry", 'distillery'=>"The Duke", 'country'=>"Germany", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Rough", 'distillery'=>"The Duke", 'country'=>"Germany", 'notes'=>'Mini','rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Wanderlust", 'distillery'=>"The Duke", 'country'=>"Germany", 'notes'=>'Mini','rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"G=in3", 'distillery'=>"Ziegler", 'country'=>"Germany", 'notes'=>'Mini','rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Elephant navy", 'distillery'=>"Elephant", 'country'=>"Germany", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Isfjord Arctic", 'distillery'=>"Isfjord", 'country'=>"Greenland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Dingle", 'distillery'=>"Dingle", 'country'=>"Ireland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Method and Madness", 'distillery'=>"Midleton", 'country'=>"Ireland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"MÃ­l", 'distillery'=>"Pearse Lyons", 'country'=>"Ireland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Drumshanbo Gunpowder", 'distillery'=>"Shed Distillery", 'country'=>"Ireland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Von Hallers", 'distillery'=>"Shed Distillery", 'country'=>"Ireland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Oâ€™ndina", 'distillery'=>"Campari", 'country'=>"Italy", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Marconi 46", 'distillery'=>"Poli", 'country'=>"Italy", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Malfy con arancia", 'distillery'=>"Torino", 'country'=>"Italy", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Malfy con limone", 'distillery'=>"Torino", 'country'=>"Italy", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Malty Rosa", 'distillery'=>"Torino", 'country'=>"Italy", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Roku", 'distillery'=>"Beam Suntory", 'country'=>"Japan", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"RoW",],
            ['name'=>"Ki No Bi - Kyoto Dry", 'distillery'=>"Kyoto", 'country'=>"Japan", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"RoW",],
            ['name'=>"Ki No Bi - Kyoto Dry Sei", 'distillery'=>"Kyoto", 'country'=>"Japan", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"RoW",],
            ['name'=>"Ki No Tea", 'distillery'=>"Kyoto", 'country'=>"Japan", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"RoW",],
            ['name'=>"Cross Keys", 'distillery'=>"Cross Keys", 'country'=>"Latvia", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Katan", 'distillery'=>"Katan", 'country'=>"Mexico", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"RoW",],
            ['name'=>"Mezcal", 'distillery'=>"Mezcal", 'country'=>"Mexico", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"RoW",],
            ['name'=>"Sloane's", 'distillery'=>"Toorank", 'country'=>"Netherlands", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Shortcross", 'distillery'=>"Rademon Estate", 'country'=>"Northern Ireland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Botanical", 'distillery'=>"Bareksten", 'country'=>"Norway", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Harahorn", 'distillery'=>"Norske Brenneri", 'country'=>"Norway", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Lighthouse", 'distillery'=>"Lighthouse", 'country'=>"NZ", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Lighthouse - Hawthorn", 'distillery'=>"Lighthouse", 'country'=>"NZ", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Scapegrace Black", 'distillery'=>"Rogue Society", 'country'=>"NZ", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Scapegrace Premium Dry", 'distillery'=>"Rogue Society", 'country'=>"NZ", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Black Robin", 'distillery'=>"Simply Pure", 'country'=>"NZ", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Glaswegin", 'distillery'=>"Glaswegin", 'country'=>"Scotland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"ANZ",],
            ['name'=>"Caorunn", 'distillery'=>"Balmenach", 'country'=>"Scotland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Vintage", 'distillery'=>"Blackwoods", 'country'=>"Scotland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Vintage 60%", 'distillery'=>"Blackwoods", 'country'=>"Scotland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Botanist", 'distillery'=>"Bruichladdich", 'country'=>"Scotland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Old Raj", 'distillery'=>"Cadenhead", 'country'=>"Scotland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Tanqueray", 'distillery'=>"Cameronbridge", 'country'=>"Scotland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Tanqueray Malacca", 'distillery'=>"Cameronbridge", 'country'=>"Scotland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Tanqueray No. Ten", 'distillery'=>"Cameronbridge", 'country'=>"Scotland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Edinburgh", 'distillery'=>"Edinburgh", 'country'=>"Scotland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Raspberry liqueur", 'distillery'=>"Edinburgh", 'country'=>"Scotland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Rhubarb & Ginger liquer", 'distillery'=>"Edinburgh", 'country'=>"Scotland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Seaside", 'distillery'=>"Edinburgh", 'country'=>"Scotland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Makar", 'distillery'=>"Glasgow", 'country'=>"Scotland", 'notes'=>'Mini','rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Hendrick's", 'distillery'=>"Hendrick's", 'country'=>"Scotland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Midsummer Solstice", 'distillery'=>"Hendrick's", 'country'=>"Scotland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Orbium", 'distillery'=>"Hendrick's", 'country'=>"Scotland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Isle of Harris", 'distillery'=>"Isle of Harris", 'country'=>"Scotland", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Clemengold", 'distillery'=>"Hope on Hopkins", 'country'=>"South Africa", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"RoW",],
            ['name'=>"Blue Gin", 'distillery'=>"Six Dogs", 'country'=>"South Africa", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"RoW",],
            ['name'=>"NordÃ©s", 'distillery'=>"Atlantic Galician", 'country'=>"Spain", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Tann's", 'distillery'=>"Campeny", 'country'=>"Spain", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Herno", 'distillery'=>"Herno", 'country'=>"Sweden", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Spirit of Hven Organic", 'distillery'=>"Spirit of Hven", 'country'=>"Sweden", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Ultra Uncut", 'distillery'=>"Strane", 'country'=>"Sweden", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Uncut", 'distillery'=>"Strane", 'country'=>"Sweden", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"Europe",],
            ['name'=>"Junipero", 'distillery'=>"Anchor", 'country'=>"USA", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"RoW",],
            ['name'=>"St George Botanivore", 'distillery'=>"St George", 'country'=>"USA", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"RoW",],
            ['name'=>"St George Terroir", 'distillery'=>"St George", 'country'=>"USA", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"RoW",],
            ['name'=>"Half Moon Orchard", 'distillery'=>"Tuthilltown", 'country'=>"USA", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"RoW",],
            ['name'=>"Freddy's Blood Gin", 'distillery'=>"Elm", 'country'=>"USA", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>'floor'],
            ['name'=>"Da Mhile Botanical", 'distillery'=>"Da Mhile", 'country'=>"Wales", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Da Mhile Seaweed", 'distillery'=>"Da Mhile", 'country'=>"Wales", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Brecon Botanical", 'distillery'=>"Penderyn", 'country'=>"Wales", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
            ['name'=>"Brecon Special Reserve", 'distillery'=>"Penderyn", 'country'=>"Wales", 'rating'=>'Unrated','status'=>'Full Bottle','shelf'=>"UKI",],
        ];


        foreach ($ginSeeder as $seed) {

            $cid = Distillery::whereName($seed['distillery'])->get();
            $did = $cid[0]['_id']; // extract the ID from the distillery data
            $data = [
                'name' => $seed['name'],
                'distillery_id' => $did,
                'rating' => $seed['rating'],
                'status' => $seed['status'],
                'shelf' => $seed['shelf']
            ];

            DB::Collection('gins')
                ->where('name', $seed['name'])
                ->where('distillery_id', $did)
                ->update($data, ['upsert' => true]);
        }
    }
}
